### ISSUE TITLE
StateTab not filtering

### ISSUE THREAD

**Issue by goldjunge4** [maartenpaauw/model-states-for-filament-docs#1]
Hello,

I am using your Model State Filament package and its working great, but one thing is not working.

First: in the doc is a slight error, you need to return the array in StateTab otherwise it will not work anyway.

```
use Maartenpaauw\Filament\ModelStates\StateTabs;
 
// ...
 
public function getTabs(): array
{
    **return** StateTabs::make($this->getModel())->toArray();
}
```
Nevertheless, with this change, it renders the tabs, but when i click on the tab, it does not filter. Could tell me what i have done wrong?

The StateSelectFilter is working perfect, so i am not sure, what the issue is.

Thanks, Armin

**Comment by maartenpaauw** [comment]
Hi! Thanks for reaching out! You're right. The docs array should be returned. I'll fix the documentation.

About the tabs that are not working; are you using another attribute name than `state`? If so. You should pass the name of the attribute as second parameter to the make method.

**Comment by goldjunge4** [comment]
Hello,

No i am working with state attribute name, but i also tried as second parameter the `state` attribute, but both is not working.
Maybe for your help, when i click on one of the tabs, the link will change to example http://domain/clean-tasks?activeTab=AppStatesCleanTaskCanceled. When i change the link manually to http://domain/clean-tasks?activeTab=App\States\CleanTask\Canceled it is working. It seems the backslashes from the class names are not inside the link.

**Comment by maartenpaauw** [comment]
Alright! Thank you so much for helping me to debug this issue. The backslashes are indeed the problem. Fortunately, spatie states can be serialized. This will fix the issue. The downside is that existing states needs to be renamed within you database.

See the official Spatie documentation about serializing the state: https://spatie.be/docs/laravel-model-states/v2/working-with-states/02-serializing-states

**Comment by goldjunge4** [comment]
Hi, yes you are right, that fixes the problem. Another question, is there a way to give the tabs a sort id, because the states in the tabs gets not sorted according there state flow direction.

**Comment by goldjunge4** [comment]
Hi, Sorry to bother you again, but i have another issue:

1. How can i change the shown name to the definied `state` attribute, because in the state attribute of each state class, there is a capital letter, example "in Prüfung" but as you can see, rendering shows small letter P
![image](https://github.com/maartenpaauw/model-states-for-filament-docs/assets/29723603/33a64c09-b951-4dff-9d65-9aec5cce5f8a)
![image](https://github.com/maartenpaauw/model-states-for-filament-docs/assets/29723603/27272aa9-6127-424d-8d03-6539ac3cc8b2)

1. I copied your lang file to german (de) file and changed the items, but the `:state` statement doesn't get rendered
![image](https://github.com/maartenpaauw/model-states-for-filament-docs/assets/29723603/cabf2ee6-7185-47a4-abd9-bd2c43bc56d8)
![image](https://github.com/maartenpaauw/model-states-for-filament-docs/assets/29723603/a2332e20-5b81-4e3a-ba8f-10ec1af4a673)

1. Last, i have in the StateClass (in my case called CleanTaskStates) on state that can be transitioned to 2 states (Implementing to Finished and Canceled possible)
```
public static function config(): StateConfig
    {
        return parent::config()
            ->default(Draft::class)
            ->allowTransition(Draft::class,Pending::class)
            ->allowTransition(Pending::class,Implementing::class)
            ->allowTransition(Implementing::class,Canceled::class)
            ->allowTransition(Implementing::class,Finished::class);
    }
```
Inside the resource i render 2 StateActions for this Change from Implementing to Finished or Canceled
```
->actions([
                Tables\Actions\ActionGroup::make([
                    StateTableAction::make('draft')->transitionTo(Pending::class),
                    StateTableAction::make('pending')->transitionTo(Implementing::class),
                    StateTableAction::make('implementing')->transitionTo(Canceled::class),
                    StateTableAction::make('implementing')->transitionTo(Finished::class),
                ])
```
![image](https://github.com/maartenpaauw/model-states-for-filament-docs/assets/29723603/e54af835-0f9f-4490-a743-6e222d7630d7)

It renders always the Actions according to the StateConfig. But if i click on Canceled, the system will always take the finished state change, also if i click on finished the finished state will choosen.

I know a lot of questions, but hopefully you can help me.

Thanks,

**Comment by maartenpaauw** [comment]
> Hi, yes you are right, that fixes the problem. Another question, is there a way to give the tabs a sort id, because the states in the tabs gets not sorted according there state flow direction.

That's currently not supported. All states are ordered alphabetically at the moment. I'm thinking about adding support for logical order. I'm not sure yet how to get it working.

**Comment by maartenpaauw** [comment]
> Hi, Sorry to bother you again, but i have another issue:
> 
> 
> 
> 1. How can i change the shown name to the definied `state` attribute, because in the state attribute of each state class, there is a capital letter, example "in Prüfung" but as you can see, rendering shows small letter P
> 
> ![image](https://github.com/maartenpaauw/model-states-for-filament-docs/assets/29723603/33a64c09-b951-4dff-9d65-9aec5cce5f8a)
> 
> ![image](https://github.com/maartenpaauw/model-states-for-filament-docs/assets/29723603/27272aa9-6127-424d-8d03-6539ac3cc8b2)
> 
> 
> 
> 1. I copied your lang file to german (de) file and changed the items, but the `:state` statement doesn't get rendered
> 
> ![image](https://github.com/maartenpaauw/model-states-for-filament-docs/assets/29723603/cabf2ee6-7185-47a4-abd9-bd2c43bc56d8)
> 
> ![image](https://github.com/maartenpaauw/model-states-for-filament-docs/assets/29723603/a2332e20-5b81-4e3a-ba8f-10ec1af4a673)
> 
> 
> 
> 1. Last, i have in the StateClass (in my case called CleanTaskStates) on state that can be transitioned to 2 states (Implementing to Finished and Canceled possible)
> 
> ```
> 
> public static function config(): StateConfig
> 
>     {
> 
>         return parent::config()
> 
>             ->default(Draft::class)
> 
>             ->allowTransition(Draft::class,Pending::class)
> 
>             ->allowTransition(Pending::class,Implementing::class)
> 
>             ->allowTransition(Implementing::class,Canceled::class)
> 
>             ->allowTransition(Implementing::class,Finished::class);
> 
>     }
> 
> ```
> 
> Inside the resource i render 2 StateActions for this Change from Implementing to Finished or Canceled
> 
> ```
> 
> ->actions([
> 
>                 Tables\Actions\ActionGroup::make([
> 
>                     StateTableAction::make('draft')->transitionTo(Pending::class),
> 
>                     StateTableAction::make('pending')->transitionTo(Implementing::class),
> 
>                     StateTableAction::make('implementing')->transitionTo(Canceled::class),
> 
>                     StateTableAction::make('implementing')->transitionTo(Finished::class),
> 
>                 ])
> 
> ```
> 
> ![image](https://github.com/maartenpaauw/model-states-for-filament-docs/assets/29723603/e54af835-0f9f-4490-a743-6e222d7630d7)
> 
> 
> 
> It renders always the Actions according to the StateConfig. But if i click on Canceled, the system will always take the finished state change, also if i click on finished the finished state will choosen.
> 
> 
> 
> I know a lot of questions, but hopefully you can help me.
> 
> 
> 
> Thanks,

Thank you for your detailed comment. I’m not able to use a computer at the moment, so the details help me a lot! 

1. If you’ve implemented the HasLabel interface on the State class, it should use the output of the getLabel method. That’s how you can customize the label of states. My two cents, you should use the static name property like the model morph class. Instead of “zu prufung”; keep the name “test” or “pending” and use the getLabel method to determine the human readable label.

2. What happens if you implement the HasLabel interface? I’m not entirely sure what’s going wrong. This because it takes the “zu” part correctly. 

3. This is because you have duplicate action names; “implementing”. These names, like every other Filament action names, should be unique. My two cents, give it the name what the action is you are doing for example; “cancel” and “finish”.

**Comment by goldjunge4** [comment]
Good morning,

Thanks for your answers.
I had `HasLabel` already inside my class, but i changed the `$name` to the same as the class is called and only inside the `getLabel` i have the name i want. This is rendered in the Table as well as in the tabs correct, but still on the action button the name is in small letters.

```
class Pending extends CleanTaskState implements HasDescription, HasColor, HasIcon, HasLabel
{
    public static $name = 'Pending';

    public function getLabel(): string
    {
        return 'in Prüfung';
    }

    public function getColor(): array
    {
        return Color::Yellow;
    }

    public function getIcon(): string
    {
        return 'heroicon-o-x-circle';
    }

    public function getDescription(): ?string
    {
        return 'Meldung erstellt, Prüfung ausständig';
    }
}
```
The rending of the notification on the top is also still showing :state

You are fully right, with the change to unique action name the action is now correct.

Thanks for your help

**Comment by goldjunge4** [comment]
Hello Maarten, sorry i have again an issue, where i dont understand where its coming from:

I have a state configured to change from informed to removed:

```
public static function config(): StateConfig
    {
        return parent::config()
            ->allowTransition(Counting::class,Informed::class)
            ->allowTransition(Informed::class,Removed::class,ToRemoved::class)
            ->allowTransition(Informed::class,Counting::class);
    }
```
and the corresponding ToRemoved class looks like this:

```
<?php

namespace App\States\FitForFuture;

use App\Models\FitForFuture;
use Filament\Forms\Components\Textarea;
use Maartenpaauw\Filament\ModelStates\Concerns\ProvidesSpatieTransitionToFilament;
use Maartenpaauw\Filament\ModelStates\Contracts\FilamentSpatieTransition;
use Spatie\ModelStates\Transition;

final class ToRemoved extends Transition implements FilamentSpatieTransition
{

    use ProvidesSpatieTransitionToFilament;

    public function __construct(
        private readonly FitForFuture $fitForFuture,
        private readonly string $reason = '',
    ) {
    }

    public function handle(): FitForFuture
    {
        $this->fitForFuture->ga_state = new Removed($this->fitForFuture);
        $this->fitForFuture->removed_at = now();
        $this->fitForFuture->removed_reason = $this->reason;

        $this->fitForFuture->save();

        return $this->fitForFuture;
    }

    public function form(): array | Closure | null
    {
        return [
            Textarea::make('reason')
                ->required()
                ->minLength(1)
                ->maxLength(125)
                ->rows(5),
        ];
    }
}
```

But during the app reload i am getting the following error:

> Could not check compatibility between App\States\FitForFuture\ToRemoved::form(): App\States\FitForFuture\Closure|array|null and Maartenpaauw\Filament\ModelStates\Contracts\FilamentSpatieTransition::form(): Closure|array|null, because class App\States\FitForFuture\Closure is not available

if i remove the `implements FilamentSpatieTransition` from the transition class, the error is gone, but the form for sure gets not rendered.

Thanks

**Comment by maartenpaauw** [comment]
> Hello Maarten, sorry i have again an issue, where i dont understand where its coming from:
> 
> I have a state configured to change from informed to removed:
> 
> ```
> public static function config(): StateConfig
>     {
>         return parent::config()
>             ->allowTransition(Counting::class,Informed::class)
>             ->allowTransition(Informed::class,Removed::class,ToRemoved::class)
>             ->allowTransition(Informed::class,Counting::class);
>     }
> ```
> 
> and the corresponding ToRemoved class looks like this:
> 
> ```
> <?php
> 
> namespace App\States\FitForFuture;
> 
> use App\Models\FitForFuture;
> use Filament\Forms\Components\Textarea;
> use Maartenpaauw\Filament\ModelStates\Concerns\ProvidesSpatieTransitionToFilament;
> use Maartenpaauw\Filament\ModelStates\Contracts\FilamentSpatieTransition;
> use Spatie\ModelStates\Transition;
> 
> final class ToRemoved extends Transition implements FilamentSpatieTransition
> {
> 
>     use ProvidesSpatieTransitionToFilament;
> 
>     public function __construct(
>         private readonly FitForFuture $fitForFuture,
>         private readonly string $reason = '',
>     ) {
>     }
> 
>     public function handle(): FitForFuture
>     {
>         $this->fitForFuture->ga_state = new Removed($this->fitForFuture);
>         $this->fitForFuture->removed_at = now();
>         $this->fitForFuture->removed_reason = $this->reason;
> 
>         $this->fitForFuture->save();
> 
>         return $this->fitForFuture;
>     }
> 
>     public function form(): array | Closure | null
>     {
>         return [
>             Textarea::make('reason')
>                 ->required()
>                 ->minLength(1)
>                 ->maxLength(125)
>                 ->rows(5),
>         ];
>     }
> }
> ```
> 
> But during the app reload i am getting the following error:
> 
> > Could not check compatibility between App\States\FitForFuture\ToRemoved::form(): App\States\FitForFuture\Closure|array|null and Maartenpaauw\Filament\ModelStates\Contracts\FilamentSpatieTransition::form(): Closure|array|null, because class App\States\FitForFuture\Closure is not available
> 
> if i remove the `implements FilamentSpatieTransition` from the transition class, the error is gone, but the form for sure gets not rendered.
> 
> Thanks

You should add a backslash before Closure or import it: use Closure;

**Comment by maartenpaauw** [comment]
> Good morning,
> 
> Thanks for your answers. I had `HasLabel` already inside my class, but i changed the `$name` to the same as the class is called and only inside the `getLabel` i have the name i want. This is rendered in the Table as well as in the tabs correct, but still on the action button the name is in small letters.
> 
> ```
> class Pending extends CleanTaskState implements HasDescription, HasColor, HasIcon, HasLabel
> {
>     public static $name = 'Pending';
> 
>     public function getLabel(): string
>     {
>         return 'in Prüfung';
>     }
> 
>     public function getColor(): array
>     {
>         return Color::Yellow;
>     }
> 
>     public function getIcon(): string
>     {
>         return 'heroicon-o-x-circle';
>     }
> 
>     public function getDescription(): ?string
>     {
>         return 'Meldung erstellt, Prüfung ausständig';
>     }
> }
> ```
> 
> The rending of the notification on the top is also still showing :state
> 
> You are fully right, with the change to unique action name the action is now correct.
> 
> Thanks for your help

Great you have figured the double action bug out. Both the label and translation issues need more investigation from my end, but I’m not in possession of my laptop for the next week. I’ll come back to the issues later on. Out did you already figure it out?

**Comment by maartenpaauw** [comment]
> Hi, Sorry to bother you again, but i have another issue:
> 
> 1. How can i change the shown name to the definied `state` attribute, because in the state attribute of each state class, there is a capital letter, example "in Prüfung" but as you can see, rendering shows small letter P
>    ![image](https://private-user-images.githubusercontent.com/29723603/341057551-33a64c09-b951-4dff-9d65-9aec5cce5f8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MTEzNjgsIm5iZiI6MTcxOTUxMTA2OCwicGF0aCI6Ii8yOTcyMzYwMy8zNDEwNTc1NTEtMzNhNjRjMDktYjk1MS00ZGZmLTlkNjUtOWFlYzVjY2U1ZjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDE3NTc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NWEwODM0NTEyNTUwODczZGM0YjYxZmQ5ZjBhOTdmNTc0NTQzNTk5NWE3MzM4MjA1MDQyMDk4OWUzNDhjOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IlJZbnkEGkkQZRkeAEbIfOqMAvETA2rVQ6qSDfuPPWo)
>    ![image](https://private-user-images.githubusercontent.com/29723603/341057887-27272aa9-6127-424d-8d03-6539ac3cc8b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MTEzNjgsIm5iZiI6MTcxOTUxMTA2OCwicGF0aCI6Ii8yOTcyMzYwMy8zNDEwNTc4ODctMjcyNzJhYTktNjEyNy00MjRkLThkMDMtNjUzOWFjM2NjOGIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDE3NTc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMDFkNTRkMzhmMzljNzU0NTI1ZjQ2NmU5MzA5MTMwZTg0NGZkZDU2OWVlOGFkY2QyNmJmN2I0M2RjOTU4MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nFihkOVrb8TEjruZxIiqA74fV8PBwyGQOB9c951_6qQ)
> 2. I copied your lang file to german (de) file and changed the items, but the `:state` statement doesn't get rendered
>    ![image](https://private-user-images.githubusercontent.com/29723603/341058719-cabf2ee6-7185-47a4-abd9-bd2c43bc56d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MTEzNjgsIm5iZiI6MTcxOTUxMTA2OCwicGF0aCI6Ii8yOTcyMzYwMy8zNDEwNTg3MTktY2FiZjJlZTYtNzE4NS00N2E0LWFiZDktYmQyYzQzYmM1NmQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDE3NTc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMDZlYWVmYWZjOGNjMGNlMDc1ZjZiNGE1YTQ2ZGRkODQ5ZWE4ZTIxYmIyZDk3ZTdhMGJjNmFkMjRlMWRkNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.019vb1KEmlAUKicSdJSuZL0hRLuPP_QM9g9Pxw32LO0)
>    ![image](https://private-user-images.githubusercontent.com/29723603/341059048-a2332e20-5b81-4e3a-ba8f-10ec1af4a673.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MTEzNjgsIm5iZiI6MTcxOTUxMTA2OCwicGF0aCI6Ii8yOTcyMzYwMy8zNDEwNTkwNDgtYTIzMzJlMjAtNWI4MS00ZTNhLWJhOGYtMTBlYzFhZjRhNjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDE3NTc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkM2U4MTMzZGY1MjFlZjQzMGM0NTAzMzU5NWQ4ZjI3MTE2OTdhMzU5NTdmZDljMWY5YjFmYjUzNjQyMGUxZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dFltJ-rCQLAvjngErgQwMtGB4jf_3xU6YADb7QgXZNk)
> 3. Last, i have in the StateClass (in my case called CleanTaskStates) on state that can be transitioned to 2 states (Implementing to Finished and Canceled possible)
> 
> ```
> public static function config(): StateConfig
>     {
>         return parent::config()
>             ->default(Draft::class)
>             ->allowTransition(Draft::class,Pending::class)
>             ->allowTransition(Pending::class,Implementing::class)
>             ->allowTransition(Implementing::class,Canceled::class)
>             ->allowTransition(Implementing::class,Finished::class);
>     }
> ```
> 
> Inside the resource i render 2 StateActions for this Change from Implementing to Finished or Canceled
> 
> ```
> ->actions([
>                 Tables\Actions\ActionGroup::make([
>                     StateTableAction::make('draft')->transitionTo(Pending::class),
>                     StateTableAction::make('pending')->transitionTo(Implementing::class),
>                     StateTableAction::make('implementing')->transitionTo(Canceled::class),
>                     StateTableAction::make('implementing')->transitionTo(Finished::class),
>                 ])
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/29723603/341061857-e54af835-0f9f-4490-a743-6e222d7630d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MTEzNjgsIm5iZiI6MTcxOTUxMTA2OCwicGF0aCI6Ii8yOTcyMzYwMy8zNDEwNjE4NTctZTU0YWY4MzUtMGY5Zi00NDkwLWE3NDMtNmUyMjJkNzYzMGQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDE3NTc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMWMzN2VkYjE0OGRjZTUyM2E4YjZiNzEyOWZhOGNmYWNmNjkwNWM5MzBmODcwYWMyMzA5YWE4NDdlOGEyMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nWHkmAAQzW6UvTYzY78t826yleV79Oqw24IE4bCNSAM)
> 
> It renders always the Actions according to the StateConfig. But if i click on Canceled, the system will always take the finished state change, also if i click on finished the finished state will choosen.
> 
> I know a lot of questions, but hopefully you can help me.
> 
> Thanks,

I'd finally had the time to dig into both issues. Let's start with issue 1: The plug-in is designed to pass an all lowercase version as `:state` to the `transition_to_state` translation key. That's why it's showing all in lowercase. The second issue is because the transitioned key intentionally never receives the `state` as a variable. That's why `:state` cannot be used and won't be replaced. See the English translation file as an example.
